version: '3.3'

services:
  db:
    #image: mysqlcompose <--- substituir por:
    build: ./mysql/ #<---build da imagem automático
    restart: always
    env_file:
      - ./config/db.env
    #ports:
     # - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    depends_on: 
      - db
    #image: flaskcompose <--- substituir por:
    build: ./flask/ #<---build da imagem automático
    ports:
      - "5000:5000"
    restart: always
    volumes:                                                                   #:/WORKDIR
      - "C:\\Users\\bruno\\DockerProjects\\compose\\6_bind_mount_compose\\flask:/app" #<---caminho para Bind Mount
    networks: 
      - dockercompose

networks:
  dockercompose: