version: '3.3'

services:
  db:
    image: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose

  backend: 
    depends_on:
      - db
    image: flaskcompose
    ports: 
      - "5000:5000"
    restart: always
    networks:
      - dockercompose

networks:
  dockercompose: